//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.6387
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesaDeAyuda.VisualWebPart {
    using System.Web;
    using System.Text.RegularExpressions;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.Security;
    using System.Text;
    using System.Web.SessionState;
    using System.Collections.Specialized;
    using Microsoft.SharePoint.WebControls;
    using System.Web.UI.WebControls;
    using System;
    using Microsoft.SharePoint;
    using System.Web.UI;
    using System.Web.Profile;
    using System.Collections;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.Caching;
    using Microsoft.SharePoint.Utilities;
    using System.Configuration;
    using System.Web.UI.HtmlControls;
    
    
    public partial class VisualWebPart {
        
        protected global::System.Web.UI.WebControls.TextBox txt_titulo;
        
        protected global::System.Web.UI.WebControls.Button btn_prueba;
        
        protected global::System.Web.UI.WebControls.Panel panel_solicitante;
        
        protected global::System.Web.UI.WebControls.TextBox txt_organizacion;
        
        protected global::System.Web.UI.WebControls.TextBox txt_dirAdjunta;
        
        protected global::System.Web.UI.WebControls.TextBox txt_dirArea;
        
        protected global::System.Web.UI.WebControls.TextBox txt_subDirArea;
        
        protected global::System.Web.UI.WebControls.TextBox txt_claveEmple;
        
        protected global::System.Web.UI.WebControls.ListBox lbx_oficina;
        
        protected global::System.Web.UI.WebControls.ListBox lbx_ubicacion;
        
        protected global::System.Web.UI.WebControls.TextBox txt_solicitante;
        
        protected global::System.Web.UI.WebControls.TextBox txt_cargo;
        
        protected global::System.Web.UI.WebControls.TextBox txt_CVU;
        
        protected global::System.Web.UI.WebControls.TextBox txt_correo;
        
        protected global::System.Web.UI.WebControls.TextBox txt_tel;
        
        protected global::System.Web.UI.WebControls.TextBox txt_ext;
        
        protected global::System.Web.UI.WebControls.TextBox txt_ubicacionExt;
        
        protected global::System.Web.UI.WebControls.TextBox txt_descripcion;
        
        protected global::System.Web.UI.WebControls.ListBox lbx_tipoServicio;
        
        protected global::System.Web.UI.WebControls.ListBox lbx_subServicio;
        
        protected global::System.Web.UI.WebControls.ListBox lbx_prioUsuario;
        
        protected global::System.Web.UI.WebControls.ListBox lbx_prioResolve;
        
        protected global::System.Web.UI.WebControls.ListBox lbx_asignacion;
        
        public static implicit operator global::System.Web.UI.TemplateControl(VisualWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_titulo() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_titulo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_titulo";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtn_prueba() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btn_prueba = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btn_prueba";
            @__ctrl.Text = "Button";
            @__ctrl.Click -= new System.EventHandler(this.btn_prueba_Click);
            @__ctrl.Click += new System.EventHandler(this.btn_prueba_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpanel_solicitante() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.panel_solicitante = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "panel_solicitante";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_organizacion() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_organizacion = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_organizacion";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_dirAdjunta() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_dirAdjunta = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_dirAdjunta";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_dirArea() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_dirArea = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_dirArea";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_subDirArea() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_subDirArea = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_subDirArea";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_claveEmple() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_claveEmple = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_claveEmple";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListBox @__BuildControllbx_oficina() {
            global::System.Web.UI.WebControls.ListBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListBox();
            this.lbx_oficina = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbx_oficina";
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(22, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListBox @__BuildControllbx_ubicacion() {
            global::System.Web.UI.WebControls.ListBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListBox();
            this.lbx_ubicacion = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbx_ubicacion";
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(22, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_solicitante() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_solicitante = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_solicitante";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_cargo() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_cargo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_cargo";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_CVU() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_CVU = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_CVU";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_correo() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_correo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_correo";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_tel() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_tel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_tel";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_ext() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_ext = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_ext";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_ubicacionExt() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_ubicacionExt = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_ubicacionExt";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_descripcion() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_descripcion = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_descripcion";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(73, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListBox @__BuildControllbx_tipoServicio() {
            global::System.Web.UI.WebControls.ListBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListBox();
            this.lbx_tipoServicio = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbx_tipoServicio";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(22, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListBox @__BuildControllbx_subServicio() {
            global::System.Web.UI.WebControls.ListBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListBox();
            this.lbx_subServicio = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbx_subServicio";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(22, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListBox @__BuildControllbx_prioUsuario() {
            global::System.Web.UI.WebControls.ListBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListBox();
            this.lbx_prioUsuario = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbx_prioUsuario";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(22, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListBox @__BuildControllbx_prioResolve() {
            global::System.Web.UI.WebControls.ListBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListBox();
            this.lbx_prioResolve = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbx_prioResolve";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(22, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListBox @__BuildControllbx_asignacion() {
            global::System.Web.UI.WebControls.ListBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListBox();
            this.lbx_asignacion = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbx_asignacion";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(22, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::MesaDeAyuda.VisualWebPart.VisualWebPart @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<!--libreria people picker-->\r\n\r\n"));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www." +
                        "w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1" +
                        "999/xhtml\"><head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=U" +
                        "TF-8\"/>\r\n<title>Smart Wizard 2 - Basic Example  - a javascript jQuery wizard con" +
                        "trol plugin</title>\r\n\r\n<link href=\"../_Layouts/MesaDeAyuda/styles/smart_wizard.c" +
                        "ss\" rel=\"stylesheet\" type=\"text/css\"/>\r\n<script type=\"text/javascript\" src=\"../_" +
                        "Layouts/MesaDeAyuda/js/jquery-1.4.2.min.js\"></script>\r\n<script type=\"text/javasc" +
                        "ript\" src=\"../_Layouts/MesaDeAyuda/js/jquery.smartWizard-2.0.js\"></script>\r\n\r\n<s" +
                        "cript type=\"text/javascript\">\r\n\r\n    function oculta(id) {\r\n        var elDiv = " +
                        "document.getElementById(id); //se define la variable \"elDiv\" igual a nuestro div" +
                        "\r\n        elDiv.style.display = \'none\'; //damos un atributo display:none que ocu" +
                        "lta el div\t \r\n    }\r\n\r\n    function muestra(id) {\r\n        var elDiv = document." +
                        "getElementById(id); //se define la variable \"elDiv\" igual a nuestro div\r\n       " +
                        " elDiv.style.display = \'block\';//damos un atributo display:block que  el div\t \r\n" +
                        "    }\r\n\r\n\r\n    window.onload = function () {/*hace que se cargue la función */\r\n" +
                        "        /* \"Mandamos como parametro el nombre de la Div para ocultar\" */\r\n      " +
                        "  oculta(\'Pmoral\'); /*Ocultamos Pmoral*/\r\n    }\r\n</script>\r\n\r\n\r\n<script type=\"te" +
                        "xt/javascript\">\r\n    $(document).ready(function () {\r\n        // Smart Wizard \t\r" +
                        "\n        $(\'#wizard\').smartWizard({\r\n            // Properties  \r\n            en" +
                        "ableAllSteps: false,  // Enable/Disable all steps on first load\r\n            tra" +
                        "nsitionEffect: \'slideleft\', // Effect on navigation, none/fade/slide/slideleft\r\n" +
                        "            enableFinishButton: false, // makes finish button enabled always\r\n  " +
                        "          labelNext: \'Siguiente\', // label for Next button\r\n            labelPre" +
                        "vious: \'Anteriro\', // label for Previous button\r\n            labelFinish: \'Final" +
                        "izar\',  // label for Finish button        \r\n            // Events\r\n            o" +
                        "nLeaveStep: null, // triggers when leaving a step\r\n            onShowStep: null," +
                        "  // triggers when showing a step\r\n            onFinish: null  // triggers when " +
                        "Finish button is clicked\r\n        });\r\n\r\n        function onFinishCallback() {\r\n" +
                        "            if (validateAllSteps()) {\r\n                $(\'form\').submit();\r\n    " +
                        "        }\r\n        }\r\n    });\r\n</script>\r\n\r\n    <style type=\"text/css\">\r\n       " +
                        " .auto-style1 {\r\n            width: 100%;\r\n        }\r\n        .auto-style2 {\r\n  " +
                        "          width: 160px;\r\n        }\r\n        </style>\r\n\r\n</head><body>\r\n\r\n<table " +
                        "align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n<tr><td> \r\n<!-- Smar" +
                        "t Wizard -->\r\n  \t\t<div id=\"wizard\" class=\"swMain\">\r\n  \t\t\t<ul>\r\n  \t\t\t\t<li><a href" +
                        "=\"#step-1\">\r\n                <label class=\"stepNumber\">1</label>\r\n              " +
                        "  <span class=\"stepDesc\">\r\n                   Nuevo Servicio<br />\r\n            " +
                        "       <small>Nuevo Elemento</small>\r\n                </span>\r\n            </a><" +
                        "/li>\r\n  \t\t\t\t<li><a href=\"#step-2\">\r\n                <label class=\"stepNumber\">2<" +
                        "/label>\r\n                <span class=\"stepDesc\">\r\n                   Tipo Solici" +
                        "tante<br />\r\n                   <small>Selecciona:</small>\r\n                </sp" +
                        "an>\r\n            </a></li>\r\n  \t\t\t\t<li><a href=\"#step-3\">\r\n                <label" +
                        " class=\"stepNumber\">3</label>\r\n                <span class=\"stepDesc\">\r\n        " +
                        "           Tipo Solicitante<br />\r\n                   <small><!--descripcion--><" +
                        "/small>\r\n                </span>                   \r\n             </a></li>\r\n  \t" +
                        "\t\t\t<li><a href=\"#step-4\">\r\n                <label class=\"stepNumber\">4</label>\r\n" +
                        "                <span class=\"stepDesc\">\r\n                   Step 4<br />\r\n      " +
                        "             <small>Step 4 description</small>\r\n                </span>         " +
                        "          \r\n            </a></li>\r\n  \t\t\t</ul>\r\n              <!--Contenido-->\r\n " +
                        " \t\t\t<div id=\"step-1\">\t\r\n            <h2 class=\"StepTitle\">Nuevo Servicio: Nuevo " +
                        "Elemento</h2>      \t\t\t\r\n                <table class=\"auto-style1\">\r\n           " +
                        "         <tr>\r\n                        <td class=\"auto-style2\">Titulo de Inciden" +
                        "cia</td>\r\n                        <td>\r\n                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxt_titulo();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        </td>
                    </tr>
                    <tr>
                        <td class=""auto-style2"">Tipo de Solicitante</td>
                        <td>
                            <label>
                                <input type=""radio"" name=""pers_cte"" value=""Estructura"" onfocus=""0""  id=""Radio1"" checked=""checked""  onclick=""muestra('PEstructura'); oculta('PExterno')""> <!-- Al cambiar 
                                ""onClick"" el valor del radio llamamos la funcion ocultando los campos de PExterno y mostrando PEstructura-->
                                    Estructura</label>
                             <br/>
                             <br/>
                             <label>
                                <input type=""radio"" name=""pers_cte"" value=""Externo"" id=""Radio2"" onclick=""muestra('PExterno'); oculta('PEstructura')""/>
                                Externo</label>
                            
                            "));
            global::System.Web.UI.WebControls.Button @__ctrl2;
            @__ctrl2 = this.@__BuildControlbtn_prueba();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        </td>
                    </tr>
                    </table>			
        </div>
  			<div id=""step-2"">
            <h2 class=""StepTitle"">Datos Generales</h2>
                  <div id=""PEstructura"">
                        <table class=""auto-style1"">
                            <tr>
                                <td class=""auto-style5"">Nombre del Solicitante</td>
                                <td>
                                    <style  type=""text/css"">    
                                .ms-inputuserfield{ font-size:8pt; font-family:Verdana,sans-serif; border:1px solid #a5a5a5;}  
                                div.ms-inputuserfield a{color:#000000;text-decoration: none;font-weight:normal;font-style:normal;}    
                                div.ms-inputuserfield{padding-left:1px;padding-top:2px;}    
                                        .auto-style5 {
                                            width: 237px;
                                        }
                                        .auto-style6 {
                                            width: 239px;
                                        }
                            </style>
                            "));
            global::System.Web.UI.WebControls.Panel @__ctrl3;
            @__ctrl3 = this.@__BuildControlpanel_solicitante();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </td>
                            </tr>
                            <tr>
                                <td class=""auto-style5"">Organizacion</td>
                                <td>
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            @__ctrl4 = this.@__BuildControltxt_organizacion();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </td>
                            </tr>
                            <tr>
                                <td class=""auto-style5"">Direccion Adjunta</td>
                                <td>
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl5;
            @__ctrl5 = this.@__BuildControltxt_dirAdjunta();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </td>
                            </tr>
                            <tr>
                                <td class=""auto-style5"">Direccion de Area</td>
                                <td>
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            @__ctrl6 = this.@__BuildControltxt_dirArea();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </td>
                            </tr>
                            <tr>
                                <td class=""auto-style5"">Subdireccion de Area</td>
                                <td>
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl7;
            @__ctrl7 = this.@__BuildControltxt_subDirArea();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </td>
                            </tr>
                            <tr>
                                <td class=""auto-style5"">Clave de Empleado</td>
                                <td>
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            @__ctrl8 = this.@__BuildControltxt_claveEmple();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                </td>\r\n                            </tr>\r\n     " +
                        "                       <tr>\r\n                                <td class=\"auto-sty" +
                        "le5\">Oficina</td>\r\n                                <td>\r\n                       " +
                        "             "));
            global::System.Web.UI.WebControls.ListBox @__ctrl9;
            @__ctrl9 = this.@__BuildControllbx_oficina();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </td>
                            </tr>
                            <tr>
                                <td class=""auto-style5"">Ubicacion Interna</td>
                                <td>
                                    "));
            global::System.Web.UI.WebControls.ListBox @__ctrl10;
            @__ctrl10 = this.@__BuildControllbx_ubicacion();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </td>
                            </tr>                            
                        </table>
                    
                    </div>
                    
                    <div id=""PExterno"">
                    <table class=""auto-style1"">                   
                        <tr>
                            <td class=""auto-style6"">Nombre del Solicitante</td>
                            <td>
                                "));
            global::System.Web.UI.WebControls.TextBox @__ctrl11;
            @__ctrl11 = this.@__BuildControltxt_solicitante();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </td>\r\n                        </tr>\r\n             " +
                        "           <tr>\r\n                            <td class=\"auto-style6\">Cargo</td>\r" +
                        "\n                            <td>\r\n                                "));
            global::System.Web.UI.WebControls.TextBox @__ctrl12;
            @__ctrl12 = this.@__BuildControltxt_cargo();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </td>\r\n                        </tr>\r\n             " +
                        "           <tr>\r\n                            <td class=\"auto-style6\">No. CVU</td" +
                        ">\r\n                            <td>\r\n                                "));
            global::System.Web.UI.WebControls.TextBox @__ctrl13;
            @__ctrl13 = this.@__BuildControltxt_CVU();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </td>\r\n                        </tr>\r\n             " +
                        "           <tr>\r\n                            <td class=\"auto-style6\">Correo Elec" +
                        "tronico</td>\r\n                            <td>\r\n                                " +
                        ""));
            global::System.Web.UI.WebControls.TextBox @__ctrl14;
            @__ctrl14 = this.@__BuildControltxt_correo();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </td>\r\n                        </tr>\r\n             " +
                        "           <tr>\r\n                            <td class=\"auto-style6\">Telefono</t" +
                        "d>\r\n                            <td>\r\n                                "));
            global::System.Web.UI.WebControls.TextBox @__ctrl15;
            @__ctrl15 = this.@__BuildControltxt_tel();
            @__parser.AddParsedSubObject(@__ctrl15);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </td>\r\n                        </tr>\r\n             " +
                        "           <tr>\r\n                            <td class=\"auto-style6\">Extension</" +
                        "td>\r\n                            <td>\r\n                                "));
            global::System.Web.UI.WebControls.TextBox @__ctrl16;
            @__ctrl16 = this.@__BuildControltxt_ext();
            @__parser.AddParsedSubObject(@__ctrl16);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </td>\r\n                        </tr>\r\n             " +
                        "           <tr>\r\n                            <td class=\"auto-style6\">Ubicacion E" +
                        "xterna</td>\r\n                            <td>\r\n                                "));
            global::System.Web.UI.WebControls.TextBox @__ctrl17;
            @__ctrl17 = this.@__BuildControltxt_ubicacionExt();
            @__parser.AddParsedSubObject(@__ctrl17);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </td>
                        </tr>
                    </table>
                    </div>
            </div>     
            <!---------------------- 3 -------------------->                          
  			<div id=""step-3"">
            <h2 class=""StepTitle"">Descripcion de la Solicitud</h2>
                <table class=""auto-style1"">
                    <tr>
                        <td>Descripcion de la Solicitud</td>
                        <td>
                                "));
            global::System.Web.UI.WebControls.TextBox @__ctrl18;
            @__ctrl18 = this.@__BuildControltxt_descripcion();
            @__parser.AddParsedSubObject(@__ctrl18);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </td>\r\n                    </tr>\r\n                 " +
                        "   <tr>\r\n                        <td>Tipo de Servicio</td>\r\n                    " +
                        "    <td>\r\n                            "));
            global::System.Web.UI.WebControls.ListBox @__ctrl19;
            @__ctrl19 = this.@__BuildControllbx_tipoServicio();
            @__parser.AddParsedSubObject(@__ctrl19);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </td>\r\n                    </tr>\r\n                    <" +
                        "tr>\r\n                        <td>Subcategoria de Servicio</td>\r\n                " +
                        "        <td>\r\n                            "));
            global::System.Web.UI.WebControls.ListBox @__ctrl20;
            @__ctrl20 = this.@__BuildControllbx_subServicio();
            @__parser.AddParsedSubObject(@__ctrl20);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </td>\r\n                    </tr>\r\n                    <" +
                        "tr>\r\n                        <td>Prioriedad de usuario</td>\r\n                   " +
                        "     <td>\r\n                            "));
            global::System.Web.UI.WebControls.ListBox @__ctrl21;
            @__ctrl21 = this.@__BuildControllbx_prioUsuario();
            @__parser.AddParsedSubObject(@__ctrl21);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </td>\r\n                    </tr>\r\n                    <" +
                        "tr>\r\n                        <td>Prioriedad de Resolvedor</td>\r\n                " +
                        "        <td>\r\n                            "));
            global::System.Web.UI.WebControls.ListBox @__ctrl22;
            @__ctrl22 = this.@__BuildControllbx_prioResolve();
            @__parser.AddParsedSubObject(@__ctrl22);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </td>\r\n                    </tr>\r\n                    <" +
                        "tr>\r\n                        <td>Asignacion</td>\r\n                        <td>\r\n" +
                        "                            "));
            global::System.Web.UI.WebControls.ListBox @__ctrl23;
            @__ctrl23 = this.@__BuildControllbx_asignacion();
            @__parser.AddParsedSubObject(@__ctrl23);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        </td>
                    </tr>
                    </table>

                                      				            
            </div>
            <!-------------------- 4 -------------------->
  			<div id=""step-4"">
            <h2 class=""StepTitle"">Asignacion</h2>
        </div>
  		</div>
<!-- End SmartWizard Content -->  		
 		
</td></tr>
</table>


    		
</body>
</html>"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
