//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.6387
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudDeServicio.VisualWebPart {
    using System.Web;
    using System.Text.RegularExpressions;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.Security;
    using System.Text;
    using System.Web.SessionState;
    using System.Collections.Specialized;
    using Microsoft.SharePoint.WebControls;
    using System.Web.UI.WebControls;
    using System;
    using Microsoft.SharePoint;
    using System.Web.UI;
    using System.Web.Profile;
    using System.Collections;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.Caching;
    using Microsoft.SharePoint.Utilities;
    using System.Configuration;
    using System.Web.UI.HtmlControls;
    
    
    public partial class VisualWebPart {
        
        protected global::System.Web.UI.WebControls.RadioButtonList RadioButtonList1;
        
        protected global::System.Web.UI.WebControls.Panel panel_solicitante;
        
        protected global::System.Web.UI.WebControls.TextBox txt_solicitud;
        
        protected global::System.Web.UI.WebControls.TextBox txt_justificacion;
        
        protected global::System.Web.UI.WebControls.Button btn_guarda;
        
        protected global::System.Web.UI.WebControls.CustomValidator CustomValidator1;
        
        protected global::System.Web.UI.WebControls.CustomValidator CustomValidator2;
        
        public static implicit operator global::System.Web.UI.TemplateControl(VisualWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control3() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Selected = false;
            @__ctrl.Value = "UsrActual";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onclick", "oculta(\'People\')");
            @__ctrl.Text = "Usuario Actual";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control4() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Selected = true;
            @__ctrl.Value = "UsrExterno";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onclick", "muestra(\'People\')");
            @__ctrl.Text = "Usuario Externo";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control3();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control4();
            @__ctrl.Add(@__ctrl2);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.RadioButtonList @__BuildControlRadioButtonList1() {
            global::System.Web.UI.WebControls.RadioButtonList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RadioButtonList();
            this.RadioButtonList1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "RadioButtonList1";
            this.@__BuildControl__control2(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpanel_solicitante() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.panel_solicitante = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "panel_solicitante";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(350, System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_solicitud() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_solicitud = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_solicitud";
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(81, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(336, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.TextMode = System.Web.UI.WebControls.TextBoxMode.MultiLine;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_justificacion() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_justificacion = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_justificacion";
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(76, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(335, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Rows = 1;
            @__ctrl.TextMode = System.Web.UI.WebControls.TextBoxMode.MultiLine;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtn_guarda() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btn_guarda = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btn_guarda";
            @__ctrl.Text = "Guardar";
            @__ctrl.Click -= new System.EventHandler(this.btn_guarda_Click);
            @__ctrl.Click += new System.EventHandler(this.btn_guarda_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.CustomValidator @__BuildControlCustomValidator1() {
            global::System.Web.UI.WebControls.CustomValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.CustomValidator();
            this.CustomValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "CustomValidator1";
            @__ctrl.ControlToValidate = "txt_solicitud";
            @__ctrl.ErrorMessage = "El campo Solicitud debe de contener un maximo de 250 caracteres";
            @__ctrl.ServerValidate -= new System.Web.UI.WebControls.ServerValidateEventHandler(this.CustomValidator1_ServerValidate);
            @__ctrl.ServerValidate += new System.Web.UI.WebControls.ServerValidateEventHandler(this.CustomValidator1_ServerValidate);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.CustomValidator @__BuildControlCustomValidator2() {
            global::System.Web.UI.WebControls.CustomValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.CustomValidator();
            this.CustomValidator2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "CustomValidator2";
            @__ctrl.ControlToValidate = "txt_solicitud";
            @__ctrl.ErrorMessage = "El campo Justificacion debe de contener un maximo de 250 caracteres";
            @__ctrl.ServerValidate -= new System.Web.UI.WebControls.ServerValidateEventHandler(this.CustomValidator1_ServerValidate);
            @__ctrl.ServerValidate += new System.Web.UI.WebControls.ServerValidateEventHandler(this.CustomValidator1_ServerValidate);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::SolicitudDeServicio.VisualWebPart.VisualWebPart @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<!--libreria people picker-->\r\n"));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<script type=""text/javascript"">

    function oculta(id) {
        var elDiv = document.getElementById(id); //se define la variable ""elDiv"" igual a nuestro div
        elDiv.style.display = 'none'; //damos un atributo display:none que oculta el div	 
    }

    function muestra(id) {
        var elDiv = document.getElementById(id); //se define la variable ""elDiv"" igual a nuestro div
        elDiv.style.display = 'block';//damos un atributo display:block que  el div	 
    }


    window.onload = function () {/*hace que se cargue la función */
        /* ""Mandamos como parametro el nombre de la Div para ocultar"" */
        oculta('Pmoral'); /*Ocultamos Pmoral*/
    }
</script>

<table>
    <tr>
        <td>
            "));
            global::System.Web.UI.WebControls.RadioButtonList @__ctrl1;
            @__ctrl1 = this.@__BuildControlRadioButtonList1();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
        </td>
        <td>
            <div id=""People"">
                <style  type=""text/css"">    
                                .ms-inputuserfield{ font-size:8pt; font-family:Verdana,sans-serif; border:1px solid #a5a5a5;}  
                                div.ms-inputuserfield a{color:#000000;text-decoration: none;font-weight:normal;font-style:normal;}    
                                div.ms-inputuserfield{padding-left:1px;padding-top:2px;}    
                                        </style>
                            "));
            global::System.Web.UI.WebControls.Panel @__ctrl2;
            @__ctrl2 = this.@__BuildControlpanel_solicitante();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            </div>\r\n            \r\n        </td>\r\n    </tr>\r\n    <tr>\r\n        <" +
                        "td>Solicitud</td>\r\n        <td>\r\n            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            @__ctrl3 = this.@__BuildControltxt_solicitud();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </td>\r\n    </tr>\r\n    <tr>\r\n        <td>Justificacion</td>\r\n        <td" +
                        ">\r\n            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            @__ctrl4 = this.@__BuildControltxt_justificacion();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </tr>\r\n    <tr>\r\n        <td>\r\n            &nbsp;</td>\r\n        <td>\r\n     " +
                        "       "));
            global::System.Web.UI.WebControls.Button @__ctrl5;
            @__ctrl5 = this.@__BuildControlbtn_guarda();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            global::System.Web.UI.WebControls.CustomValidator @__ctrl6;
            @__ctrl6 = this.@__BuildControlCustomValidator1();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            <br />\r\n            "));
            global::System.Web.UI.WebControls.CustomValidator @__ctrl7;
            @__ctrl7 = this.@__BuildControlCustomValidator2();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </td>\r\n    </tr>\r\n</table>"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
